swagger: '2.0'
info:
  title: term_plans
  version: 1.0.0
  description: term_plans
paths:
  /plan:
    get:
      operationId: getPlan
      responses:
        '200':
          description: The operation was successful.
          schema:
            type: array
            items:
              $ref: '#/definitions/plan'
      produces:
        - application/json
      description: Retrieve plan
basePath: /term_plans/v1
definitions:
  plan:
    type: object
    properties:
      name:
        type: string
      annualPremium:
        type: number
      payingTerms:
        type: integer
      sumAssured:
        type: number
schemes:
  - https
securityDefinitions: {}
security: []
